[WIP] Clashing defines on Windows.
1.

In file included from ../../brave/browser/ui/views/frame/brave_browser_view.cc:6:
../..\brave/browser/ui/views/frame/brave_browser_view.h(144,27): error: only virtual member functions can be marked 'override'
  144 |   void LoadAccelerators() override;
      |                           ^~~~~~~~

---------------------------------------

2.

/GR- -I../../third_party/libc++/src/include /Fd"obj/brave/browser/ui/ui_cc.pdb"
In file included from ../../brave/browser/ui/views/frame/brave_browser_view.cc:33:
In file included from ../..\brave/browser/ui/views/brave_actions/brave_shields_action_view.h:13:
In file included from ../..\brave/browser/ui/brave_shields_data_controller.h:16:
In file included from gen\brave/components/brave_shields/core/common/brave_shields_panel.mojom.h:28:
gen\brave/components/brave_shields/core/common/brave_shields_panel.mojom-shared.h(90,3): error: expected identifier
   90 |   STRICT = 0,
      |   ^
../../third_party/depot_tools/win_toolchain/vs_files/d325744cf9\Windows Kits\10\Include\10.0.22621.0\shared\minwindef.h(23,16): note: expanded from macro 'STRICT'
   23 | #define STRICT 1
      |                ^
In file included from ../../brave/browser/ui/views/frame/brave_browser_view.cc:33:
In file included from ../..\brave/browser/ui/views/brave_actions/brave_shields_action_view.h:13:
In file included from ../..\brave/browser/ui/brave_shields_data_controller.h:16:
In file included from gen\brave/components/brave_shields/core/common/brave_shields_panel.mojom.h:28:
gen\brave/components/brave_shields/core/common/brave_shields_panel.mojom-shared.h(126,3): error: expected identifier
  126 |   STRICT = 0,
      |   ^
../../third_party/depot_tools/win_toolchain/vs_files/d325744cf9\Windows Kits\10\Include\10.0.22621.0\shared\minwindef.h(23,16): note: expanded from macro 'STRICT'
   23 | #define STRICT 1
      |                ^
2 errors generated.

---------------------------------------

3.

FAILED: chrome.dll chrome.dll.lib chrome.dll.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe "/OUT:./chrome.dll" /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\19\lib\windows /winsysroot:../../third_party/depot_tools/win_toolchain/vs_files/d325744cf9 /MACHINE:X64  "/IMPLIB:./chrome.dll.lib" /DLL "/PDB:./chrome.dll.pdb" "@./chrome.dll.rsp"
lld-link: error: undefined symbol: public: class std::__Cr::basic_string<char16_t, struct std::__Cr::char_traits<char16_t>, class std::__Cr::allocator<char16_t>> __cdecl ProfileAttributesEntry::GetUserNameW(void) const
>>> referenced by .\..\..\chrome\browser\ui\views\profiles\profile_picker_flow_controller.cc:324
>>>               obj/chrome/browser/ui\ui/profile_picker_flow_controller.obj:(class std::__Cr::unique_ptr<class ProfileManagementStepController, struct std::__Cr::default_delete<class ProfileManagementStepController>> __cdecl `anonymous namespace'::CreateReauthtep(class ProfilePickerWebContentsHost *, class Profile *, class base::OnceCallback<void __cdecl(bool, enum ReauthUIError)>))